spring:
  profiles:
    active:  # 1. change active profile to local profile
    group:   # 2. add local profile to profile group
      prod:
        - common
      test:
        - common
---
spring:
  config:
    activate:
      on-profile: common

jwt:
  secret-key: 2023-wanted-internship-siren-order-project.secret_key
  access-token.expire-time-ms: 43200000 #12시간
  refresh-token.expired-time-ms: 604800000 #7일

---

### 3. create local profile setting

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect=org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console